name: Feature Request / Enhancement
description: Suggest a new feature or enhancement to SCS
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

        **Note**: For major changes to the specification, please open a Discussion first or submit an RFC.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of SCS would this affect?
      options:
        - Specification (spec/)
        - Schemas (schema/)
        - Templates (templates/)
        - Documentation (docs/)
        - Examples
        - Tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Is this a minor enhancement or major change?
      options:
        - Minor (clarification, example, small addition)
        - Major (new concept, breaking change) - Should be an RFC
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it support?
      placeholder: Describe the problem or gap this addresses
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this problem?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references.
    validations:
      required: false
